server:
  port: 8080 #服务监听端口
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sys #数据库连接地址
    driver-class-name: com.mysql.cj.jdbc.Driver #配置MYSQL的驱动程序类
  jpa:
    hibernate:
      ddl-auto: update #表示如果表不存在，则会根据实体类生成表，如果存在，就根据实体类更新表
    database-platform: org.hibernate.dialect.MYSQL5InnoDBDialect #指定使用哪种MYSQL存储引擎，在此是InnoDB
    open-in-view: false